### ISSUE TITLE
Raise 「NoMethodError: undefined method `decorate'」 when using decorate method in around hooks

### ISSUE THREAD

**Issue by ghost** [mizoR/active_decorator-rspec#10]
## Abstract

I execute below spec and display `NoMethodError: undefined method 'decorate' for #<RSpec::ExampleGroups::UserDecorator:0x00007ff9e0804170>`.

```ruby
require 'rails_helper'

RSpec.describe UserDecorator do
  let(:user) { User.new(first_name: 'first_name', last_name: 'last_name') }

  around do |example|
    decorate(user)

    example.run
  end

  it{ expect(user.full_name).to eq 'first_name last_name' }
end
```

## Steps to reproduce

This is  reproduced Rails application.

1. git clone `git@github.com:taki/active_decorator-rspec-using-around.git`
1. cd active_decorator-rspec-using-around
1. bundle install
1. bin/rails db:setup
1. bundle exec rspec spec/decorators/user_decorator_spec.rb

## Expected behavior

Test is passed.

## Actual behavior

「NameError: undefined local variable or method `view_context'」 is displayed.

## System configuration

- Rails version 5.2.1
- active_decorator 1.1.1
- active_decorator-rspec0.0.9

**Comment by mizoR** [comment]
Thanks for reporting it.  Sorry but I don't know the correct approach to improve it for now, so I couldn't fix it soon.  But a following patch might be a workaround for this issue.

```patch
diff --git a/spec/decorators/user_decorator_spec.rb b/spec/decorators/user_decorator_spec.rb
index 08bd9d7..8a0bf73 100644
--- a/spec/decorators/user_decorator_spec.rb
+++ b/spec/decorators/user_decorator_spec.rb
@@ -3,6 +3,15 @@ require 'rails_helper'
 RSpec.describe UserDecorator do
   let(:user) { User.new(first_name: 'first_name', last_name: 'last_name') }

+  # HACK: Prevent to enable ActiveDecorator::RSpec automatically, and enable it manually
+  around do |example|
+    example.metadata[:type] = nil if example.metadata[:type] == :decorator
+
+    ActiveDecorator::RSpec.enable(self)
+
+    example.run
+  end
+
   around do |example|
     decorate(user)
```

Thanks

**Comment by ghost** [comment]
Thank you for replying. Do not mind.

**Comment by ghost** [comment]
This is inactive. So, I will close this.
